language: shell
script:
    - chmod o+x ./scripts/aws_dist.sh
    - ls -a
    - /usr/bin/env  ./scripts/aws_dist.sh
    - ls -a dist
deploy:
    provider: releases
    email: lit468@163.com
    password: li123!@#qwe
    api_key:
        secure: ${GH_TOKEN1}
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
        repo: scannme/DPDK 
        branch: master 

