language: shell
script:
    - chmod o+x ./scripts/aws_dist.sh
    - ls -a
    - /usr/bin/env  ./scripts/aws_dist.sh
    - ls -a dist
deploy:
    provider: releases
    user: "lit468@163.com"
    password: "li123!@#qwe"
    file: dist/fortiweb-ha-auto-deploy-aws.zip
    file_glob: true
    skip_cleanup: true
    on: 
      branch: master
   

