language: shell
script:
    - chmod o+x ./scripts/aws_dist.sh
    - ls -a
    - /usr/bin/env  ./scripts/aws_dist.sh
    - ls -a dist
deploy:
    provider: release
    api_key:
        secure: 4dbb6b11a0bbaba0be48c79f0ba4366843e30130
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
        repo: scannme/DPDK
        tags: true
        branch: master 

